"""Added test db

Revision ID: 4120df8ee7cd
Revises: 
Create Date: 2023-02-26 22:32:26.403329

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4120df8ee7cd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vk_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=64), nullable=False),
    sa.Column('last_name', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_players_first_name'), 'players', ['first_name'], unique=False)
    op.create_index(op.f('ix_players_last_name'), 'players', ['last_name'], unique=False)
    op.create_index(op.f('ix_players_vk_id'), 'players', ['vk_id'], unique=True)
    op.create_table('themes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_themes_title'), 'themes', ['title'], unique=True)
    op.create_table('questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('theme_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['theme_id'], ['themes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_questions_theme_id'), 'questions', ['theme_id'], unique=False)
    op.create_index(op.f('ix_questions_title'), 'questions', ['title'], unique=True)
    op.create_table('answers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=64), nullable=False),
    sa.Column('is_correct', sa.BOOLEAN(), nullable=True),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_answers_question_id'), 'answers', ['question_id'], unique=False)
    op.create_index(op.f('ix_answers_title'), 'answers', ['title'], unique=False)
    op.create_table('games',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('state', sa.String(length=64), nullable=False),
    sa.Column('who_next', postgresql.ARRAY(sa.Integer(), dimensions=1), nullable=True),
    sa.Column('question_id', sa.Integer(), nullable=True),
    sa.Column('word', sa.String(length=64), nullable=True),
    sa.CheckConstraint("((state)::text = ANY (ARRAY[('Created'::character varying)::text,                     ('Started'::character varying)::text, ('Stoped'::character varying)::text]))", name='games_state_check'),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_games_question_id'), 'games', ['question_id'], unique=False)
    op.create_index(op.f('ix_games_state'), 'games', ['state'], unique=False)
    op.create_table('association_table',
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('player_id', 'game_id')
    )
    op.create_table('scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('player_vk_id', sa.Integer(), nullable=True),
    sa.Column('game_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.ForeignKeyConstraint(['player_vk_id'], ['players.vk_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scores_game_id'), 'scores', ['game_id'], unique=False)
    op.create_index(op.f('ix_scores_player_vk_id'), 'scores', ['player_vk_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scores_player_vk_id'), table_name='scores')
    op.drop_index(op.f('ix_scores_game_id'), table_name='scores')
    op.drop_table('scores')
    op.drop_table('association_table')
    op.drop_index(op.f('ix_games_state'), table_name='games')
    op.drop_index(op.f('ix_games_question_id'), table_name='games')
    op.drop_table('games')
    op.drop_index(op.f('ix_answers_title'), table_name='answers')
    op.drop_index(op.f('ix_answers_question_id'), table_name='answers')
    op.drop_table('answers')
    op.drop_index(op.f('ix_questions_title'), table_name='questions')
    op.drop_index(op.f('ix_questions_theme_id'), table_name='questions')
    op.drop_table('questions')
    op.drop_index(op.f('ix_themes_title'), table_name='themes')
    op.drop_table('themes')
    op.drop_index(op.f('ix_players_vk_id'), table_name='players')
    op.drop_index(op.f('ix_players_last_name'), table_name='players')
    op.drop_index(op.f('ix_players_first_name'), table_name='players')
    op.drop_table('players')
    # ### end Alembic commands ###
