"""Added admin tables

Revision ID: e41ced43024e
Revises: 4120df8ee7cd
Create Date: 2023-02-28 23:51:19.591672

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e41ced43024e'
down_revision = '4120df8ee7cd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
